package rules;

import com.ftn.sbnz.model.models.Violation;
import com.ftn.sbnz.model.models.FinalDecision;
import com.ftn.sbnz.model.models.DriverValidity;
import com.ftn.sbnz.model.models.PermitStatus;
import com.ftn.sbnz.model.enums.ViolationType;
import com.ftn.sbnz.model.enums.ActionRecommendation;
import com.ftn.sbnz.model.enums.ValidityStatus;


rule "Final decision ARREST"
    salience 200
    when
        DriverValidity(status == ValidityStatus.ARREST)
        not FinalDecision()
    then
        FinalDecision decision = new FinalDecision();
        decision.setRecommendation(ActionRecommendation.ARREST);
        decision.setTotalFine(0.0);
        decision.setRequiresDriverReplacement(false);
        decision.setRequiresCargoOffLoad(false);
        decision.setEntryRefusalCertificate(
                "POTVRDA O LISAVANJU SLOBODE: Vozac je evidentiran u bazi potrage. Pokrece se zakonska procedura." +
                "Potvrda se izdaje u 3 primerka."
        );
        insert(decision);
end


rule "Final decision FORBID ENTRY"
    salience 190
    when
        PermitStatus()
        Violation(canContinue == false)
        $totalFine: Double() from accumulate(
            Violation($fine: fineAmount, $fine != null),
            sum($fine)
        )
        not FinalDecision()
    then
        FinalDecision decision = new FinalDecision();
        decision.setRecommendation(ActionRecommendation.FORBID_ENTRY);
        decision.setTotalFine($totalFine);
        decision.setRequiresDriverReplacement(false);
        decision.setRequiresCargoOffLoad(false);
        decision.setEntryRefusalCertificate(
            "POTVRDA O ODBIJANJU ULASKA: Utvrdjena krsenja sprecavaju prelazak granice. " +
            "Detalji svakog krsenja i zakonski osnov navedeni su u prilogu. " +
            "Vozac ima pravo zalbe u skladu sa zakonom."
        );
        insert(decision);
end


rule "Final decision HOLD FINE"
    salience 180
    when
        PermitStatus()
        not Violation(canContinue == false)
        exists Violation()
        $totalFine: Double() from accumulate(
            Violation($fine: fineAmount, $fine != null),
            sum($fine)
        )
        not FinalDecision()
    then
        FinalDecision decision = new FinalDecision();
        decision.setRecommendation(ActionRecommendation.HOLD_FINE);
        decision.setTotalFine($totalFine);
        decision.setRequiresDriverReplacement(false);
        decision.setRequiresCargoOffLoad(false);
        insert(decision);
end


rule "Final decision ALLOW"
    salience 170
    when
        PermitStatus()
        not Violation()
        not FinalDecision()
    then
        FinalDecision decision = new FinalDecision();
        decision.setRecommendation(ActionRecommendation.ALLOW);
        decision.setTotalFine(0.0);
        decision.setRequiresDriverReplacement(false);
        decision.setRequiresCargoOffLoad(false);
        insert(decision);
end