package com.ftn.sbnz.model.enums;

public enum GoodsCertificate {
    ADR_CERTIFICATE,
    VETERINARY_CERTIFICATE,
    ATP_CERTIFICATE,
    WASTE_TRANSPORT_CERTIFICATE,
    PHARMACEUTICAL_CERTIFICATE,
    RADIOACTIVE_CERTIFICATE,
    EXPLOSIVES_CERTIFICATE
}
