package com.ftn.sbnz.model.enums;

public enum ViolationType {
    EXPIRED_DRIVING_LICENCE,
    INVALID_DRIVING_CATEGORY,
    EXPIRED_ID_CARD,
    EXPIRED_PASSPORT,
    PASSPORT_SHORT_VALIDITY,
    SUSPECTED_FORGERY,
    STOLEN_LOST_DOCUMENT,
    MISSING_VISA_SUPPLEMENT,
    INSUFFICIENT_FUNDS,
    TRAILER_OVERLOAD,
    TOTAL_WEIGHT_OVERLOAD,
    MISSING_THIRD_COUNTRY_PERMIT,
    INTERPOL_WARRANT,
    DOMESTIC_WARRANT,
    EXPIRED_REGISTRATION,
    PENDING_WEIGHT_CHECK
}
